---

- name: Downloading Files with aws-cli sync
  shell: AWS_ACCESS_KEY_ID={{ aws_s3_access_key }} AWS_SECRET_ACCESS_KEY={{ aws_s3_secret_key }} aws s3 sync s3://{{ aws_s3_bucket }}{{ aws_s3_sync_origin }} {{ aws_s3_sync_dest }}
  when: aws_s3_download_mode == "aws-cli"

- name: Downloading Files with ansible s3
  s3: region="{{ aws_s3_region }}"
      aws_access_key="{{ aws_s3_access_key }}"
      aws_secret_key="{{ aws_s3_secret_key }}"
      bucket="{{ aws_s3_bucket }}"
      object="{{ item.object }}"
      dest="{{ item.dest }}"
      mode="{{ aws_s3_mode }}"
      #overwrite=different
  with_items: "{{ aws_s3_get_files }}"
  when: aws_s3_download_mode == "ansible-s3"
