
- name: Installing requirements to use AWS
  apt: name={{item}} state=latest
  with_items:
    - python
    - python-pip

- name: Installing AWS requirements
  pip: name={{ item }}
  with_items:
    - boto
    - awscli

- name: Downloading Files
  shell: AWS_ACCESS_KEY_ID={{ aws_s3_access_key }} AWS_SECRET_ACCESS_KEY={{ aws_s3_secret_key }} aws s3 sync s3://{{ aws_s3_bucket }} /tmp
  with_items: "{{ aws_s3_get_files }}"
  when: aws_s3_download_mode == "aws-cli"

- name: Downloading S3 files
  s3: region="{{ aws_s3_region }}"
      aws_access_key="{{ aws_s3_access_key }}"
      aws_secret_key="{{ aws_s3_secret_key }}"
      bucket="{{ aws_s3_bucket }}"
      object="{{ item.object }}"
      dest="{{ item.dest }}"
      mode="{{ aws_s3_mode }}"
  with_items: "{{ aws_s3_get_files }}"
  when: aws_s3_download_mode == "ansible-s3"