
- name: Installing requirements to use AWS
  apt: name={{item}} state=latest
  with_items:
    - python
    - python-pip

- name: Installing BOTO.
  pip: name=boto

- name: Downloading S3 files
  s3: region="{{ aws_s3_region }}"
      aws_access_key="{{ aws_s3_access_key }}"
      aws_secret_key="{{ aws_s3_secret_key }}"
      bucket="{{ aws_s3_bucket }}"
      object="{{ item.object }}"
      dest="{{ item.dest }}"
      mode="{{ aws_s3_mode }}"
  with_items: "{{ aws_s3_get_files }}"
