---

- name: Installing requirements to use AWS
  apt: name={{item}} state=latest
  with_items:
    - python
    - python-pip
    - python-setuptools

- name: Installing AWS requirements
  pip: name={{ item }}
  with_items:
    - boto
    - awscli
